variable branch {}
variable backend_consul_root_password {}
variable consul_data_volume_size {}
variable consul_instance_type {}
variable cluster_id {}
variable project_dir {}
variable terraform_project_url {}
variable bootstrapper_image {}
variable controller_image {}
variable k8s_namespace {}
variable k8s_storage_class_name {}
variable region {}
variable region_id {}
variable ucloud_pub_key {}
variable ucloud_secret {}
variable project_id {}
variable ucloud_api_base_url {}
variable controller_cidr {}
variable mgrVpcCidr {}
variable clientVpcCidr {}
variable allow_ip {}
variable az {
  type = list(string)
}
variable ipv6_api_url {}
variable consul_server_image_id {}
variable consul_server_root_password {}
variable consul_server_type {}
variable nomad_client_broker_type {}
variable nomad_client_image_id {}
variable nomad_client_namesvr_type {}
variable nomad_client_root_password {}
variable nomad_server_image_id {}
variable nomad_server_root_password {}
variable nomad_server_type {}